name: Build and Deploy to Somee

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-build -o ./publish

      - name: Deploy to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 155.254.244.30
          username: ashir_ali
          password: developer@72
          local-dir: ./publish/
          server-dir: /www.boostinghub.somee.com/
          protocol: ftp
          dry-run: false
